CREATE TABLE IF NOT EXISTS foundation_verification (
  id INT AUTO_INCREMENT PRIMARY KEY,
  verification_key VARCHAR(100) NOT NULL UNIQUE,
  verification_value VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
