CREATE TABLE IF NOT EXISTS boardings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customer_id INT NOT NULL,
  pet_id INT NOT NULL,
  service_id INT NOT NULL,
  appointment_id INT NULL,
  daily_operation_id INT NULL,
  expected_check_in DATETIME NULL,
  expected_check_out DATETIME NULL,
  actual_check_in TIMESTAMP NULL,
  actual_check_out TIMESTAMP NULL,
  status ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED') NOT NULL DEFAULT 'PENDING',
  before_condition TEXT NULL,
  actual_boarding_content TEXT NULL,
  boarding_result TEXT NULL,
  note TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_boardings_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_boardings_pet FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE RESTRICT,
  CONSTRAINT fk_boardings_service FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE RESTRICT,
  CONSTRAINT fk_boardings_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE RESTRICT,
  CONSTRAINT fk_boardings_daily_operation FOREIGN KEY (daily_operation_id) REFERENCES daily_operations(id) ON DELETE SET NULL,
  INDEX idx_boardings_pet_status (pet_id, status),
  INDEX idx_boardings_daily_operation_id (daily_operation_id),
  INDEX idx_boardings_appointment_id (appointment_id)
);
