-- This migration intentionally contains no schema changes.
-- The customer and pet profile fields below were already created in
-- 004_create_pet_management.sql and must not be added again.
--
-- customers.id_card_number
-- customers.emergency_contact_name
-- customers.emergency_contact_phone
-- pets.personality
-- pets.medical_history
-- pets.other_history

